package com.schoolenglishmedium.teacher.retrofit_api;

public class ServerConfig {
    static String BASE_URL = "http://demoserversapps.com/demoschoolportal/public/api/teachers/";
    static final String LOGIN_API = "login";
    static final String OTP_API = "otpVerify";
    static final String TEACHER_PROFILE_API = "getTeacherUserDetail";
    static final String GET_STUDENT_LIST_API = "getAllStudentlist";
    static final String SELECT_STUDENT_API = "selectStudent";
    static final String HOME_WORK_LIST_API = "getHomeWorklist";
    static final String GET_ATTENDANCE_LIST_API = "getAttandanceStudentlist";
    static final String GET_SYLLABUS_LIST_API = "getSyllabuslist";
    static final String GET_NOTICE_LIST_API = "getNoticeBoardlist";
    static final String GET_FOOD_MENU_LIST_API = "getFoodMenulist";
    static final String GET_CO_CURRICULUM_ACTIVITY_LIST_API = "coActivity";
    static final String GET_EVENT_LIST_API = "getEventslist";
    static final String UPLOAD_HOMEWORK_API = "uploadHomework";
    static final String GET_GALLERY_API = "getGallerylist";
    static final String GET_ACTIVITY_API = "teacherActivity";
    static final String GET_TEACHER_LEAVE_API = "teacherLeave";
    static final String GET_CLASS_LIST_API = "getClasslist";
    static final String GET_SECTION_LIST_API = "getSectionlist";
    static final String TAKE_ATTENDANCE_API = "takeAttandence";
    static final String GET_HOMEWORK_UPDATE_API = "getHomeWorkUpdate";
    static final String UPDATE_HOMEWORK_API = "saveHomeWorkUpdateComment";
    static final String NEW_LEAVE_REQUEST_API = "addTeacherLeave";
    static final String EDIT_LEAVE_REQUEST_API = "editTeacherLeave";
    static final String GET_TO_DO_NOTES_API = "teacherActivityNotes";
    static final String ADD_TO_DO_NOTES_API = "addTeacherActivityNotes";
    static final String EDIT_TO_DO_NOTES_API = "editTeacherActivityNotes";
    static final String GET_SUBJECTS_API = "getSubjectlist";
    static final String ADD_SYLLABUS = "addSyllabus";
    static final String UPDATE_SYLLABUS = "editSyllabus";
    static final String GET_SYLLABUS_UPDATE_DETAILS = "getSyllabusUpdatelist";
    static final String ADD_SYLLABUS_UPDATE_DETAILS = "addSyllabusUpdate";
    static final String EDIT_SYLLABUS_UPDATE_DETAILS = "editSyllabusUpdate";
    static final String ADD_HOMEWORK = "addHomeWork";
    static final String UPDATE_HOMEWORK = "updateHomeWork";
    static final String ADD_NOTICE = "addNoticeBoardlist";
    static final String UPDATE_NOTICE = "editNoticeBoardlist";
    static final String STUDENT_ACTIVITY_API = "studentActivity";
    static final String ADD_STUDENT_ACTIVITY_API = "addStudentActivity";
    static final String UPDATE_STUDENT_ACTIVITY_API = "editStudentActivity";
}
